import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/animation/ModeToggle";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider enableSystem disableTransitionOnChange>
          {" "}
          <ModeToggle />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
