import { ThemeProvider } from "@/components/theme-provider";
import CHeader from "./components/CHeader";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <main className="min-h-screen w-full ">
      <CHeader />
      {children}
    </main>
  );
}
