import { CHeader } from "./components/CHeader";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="min-h-screen w-full ">
      <CHeader />
      {children}
    </div>
  );
}
